In [1]:
import pandas as pd
import re

df = pd.read_csv("../data/raw/deceptive-opinion.csv")
df.head()

,deceptive,hotel,polarity,source,text
0,truthful,conrad,positive,TripAdvisor,We stayed for a one night getaway with family ...
1,truthful,hyatt,positive,TripAdvisor,Triple A rate with upgrade to view room was le...
2,truthful,hyatt,positive,TripAdvisor,This comes a little late as I'm finally catchi...
3,truthful,omni,positive,TripAdvisor,The Omni Chicago really delivers on all fronts...
4,truthful,hyatt,positive,TripAdvisor,I asked for a high floor away from the elevato...

In [2]:
print("Önce:", df.shape)
print("Duplicate text sayısı:", df["text"].duplicated().sum())

df = df.drop_duplicates(subset=["text"]).reset_index(drop=True)

print("Sonra:", df.shape)
print("Duplicate text sayısı:", df["text"].duplicated().sum())

Önce: (1600, 5)
Duplicate text sayısı: 4
Sonra: (1596, 5)
Duplicate text sayısı: 0

In [3]:
df = df[["text", "deceptive"]].copy()

print("Yeni shape:", df.shape)
df.head()

Yeni shape: (1596, 2)

                                                text deceptive
0  We stayed for a one night getaway with family ...  truthful
1  Triple A rate with upgrade to view room was le...  truthful
2  This comes a little late as I'm finally catchi...  truthful
3  The Omni Chicago really delivers on all fronts...  truthful
4  I asked for a high floor away from the elevato...  truthful

In [4]:
df["label"] = df["deceptive"].map({
    "truthful": 0,
    "deceptive": 1
})

print(df[["deceptive", "label"]].head())
print("\nLabel dağılımı:")
print(df["label"].value_counts())

  deceptive  label
0  truthful      0
1  truthful      0
2  truthful      0
3  truthful      0
4  truthful      0

Label dağılımı:
label
1    800
0    796
Name: count, dtype: int64

In [6]:
def clean_text(text):
    text = text.lower()                       # küçük harfe çevir
    text = re.sub(r"[^a-zA-Z\s]", " ", text) # harf ve boşluk dışını temizle
    text = re.sub(r"\s+", " ", text).strip() # fazla boşlukları temizle
    return text

In [7]:
df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text", "label"]].head()

,text,clean_text,label
0,We stayed for a one night getaway with family ...,we stayed for a one night getaway with family ...,0
1,Triple A rate with upgrade to view room was le...,triple a rate with upgrade to view room was le...,0
2,This comes a little late as I'm finally catchi...,this comes a little late as i m finally catchi...,0
3,The Omni Chicago really delivers on all fronts...,the omni chicago really delivers on all fronts...,0
4,I asked for a high floor away from the elevato...,i asked for a high floor away from the elevato...,0

In [8]:
print("Final shape:", df.shape)
print("\nEksik değerler:")
print(df.isnull().sum())

Final shape: (1596, 4)

Eksik değerler:
text          0
deceptive     0
label         0
clean_text    0
dtype: int64

In [9]:
df.to_csv("../data/processed/clean_reviews.csv", index=False)
print("Kaydedildi: ../data/processed/clean_reviews.csv")

Kaydedildi: ../data/processed/clean_reviews.csv