In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("../data/processed/clean_reviews.csv")
df.head()

,text,deceptive,label,clean_text
0,We stayed for a one night getaway with family ...,truthful,0,we stayed for a one night getaway with family ...
1,Triple A rate with upgrade to view room was le...,truthful,0,triple a rate with upgrade to view room was le...
2,This comes a little late as I'm finally catchi...,truthful,0,this comes a little late as i m finally catchi...
3,The Omni Chicago really delivers on all fronts...,truthful,0,the omni chicago really delivers on all fronts...
4,I asked for a high floor away from the elevato...,truthful,0,i asked for a high floor away from the elevato...

In [2]:
X = df["clean_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print(X_train_tfidf.shape, X_test_tfidf.shape)

(1276, 5000) (320, 5000)

In [3]:
logreg = LogisticRegression(random_state=42, max_iter=1000)
logreg.fit(X_train_tfidf, y_train)

y_pred_logreg = logreg.predict(X_test_tfidf)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_logreg))
print(classification_report(y_test, y_pred_logreg))

Logistic Regression Accuracy: 0.890625
              precision    recall  f1-score   support

           0       0.91      0.86      0.89       160
           1       0.87      0.92      0.89       160

    accuracy                           0.89       320
   macro avg       0.89      0.89      0.89       320
weighted avg       0.89      0.89      0.89       320

In [4]:
nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

y_pred_nb = nb.predict(X_test_tfidf)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

Naive Bayes Accuracy: 0.859375
              precision    recall  f1-score   support

           0       0.90      0.81      0.85       160
           1       0.82      0.91      0.87       160

    accuracy                           0.86       320
   macro avg       0.86      0.86      0.86       320
weighted avg       0.86      0.86      0.86       320

In [5]:
results = pd.DataFrame({
    "Model": ["Logistic Regression", "Multinomial Naive Bayes"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_logreg),
        accuracy_score(y_test, y_pred_nb)
    ]
})

results

                     Model  Accuracy
0      Logistic Regression  0.890625
1  Multinomial Naive Bayes  0.859375